name: Build and Parallel Jobs Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

  job_1:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # - name: Download node_modules artifact
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: node_modules

      # - name: Extract node_modules
      #   run: |
      #     tar -xzf node_modules.tar.gz

      - name: Run build with Broker A
        env:
          BROKER: broker_a
        run: npm run build

  job_2:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # - name: Download node_modules artifact
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: node_modules

      # - name: Extract node_modules
      #   run: |
      #     tar -xzf node_modules.tar.gz

      - name: Run build with Broker B
        env:
          BROKER: broker_b
        run: npm run build

  # Add more jobs as needed, using the same structure as job_1 and job_2.
