name: Build and Parallel Jobs Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20,
          cache: "npm"

      - name: Install dependencies
        run: npm ci

  job_1:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Run build with Broker A
        env:
          BROKER: broker_a
        run: npm run build

  job_2:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Run build with Broker B
        env:
          BROKER: broker_b
        run: npm run build

  # Add more jobs as needed, using the same structure as job_1 and job_2.
